package org.km.llmwiki.mcp;

/** Typed MCP tool error taxonomy; messages are operator-safe and never carry internals. */
public enum McpToolError {
    INVALID_REQUEST,
    NOT_FOUND,
    RETRIEVAL_UNAVAILABLE,
    INSUFFICIENT_EVIDENCE,
    PROVIDER_CONFIGURATION_UNAVAILABLE,
    PROVIDER_AUTHENTICATION_OR_AUTHORIZATION,
    PROVIDER_RATE_LIMIT_OR_QUOTA,
    PROVIDER_TIMEOUT_OR_NETWORK_UNAVAILABLE,
    PROVIDER_SERVER_FAILURE,
    PROVIDER_INVALID_RESPONSE,
    LOCAL_VALIDATION,
    AUTHENTICATION_FAILED,
    PAYLOAD_TOO_LARGE,
    MCP_DISABLED
}
